### ISSUE TITLE
Work with us on `build-gradle`?

### ISSUE THREAD

**Issue by keplersj** [henjue/atom-gradle-manager#1]
This is an awesome package you've made! @noseglid and I have been working on a Gradle provider for the `build` package, which has modular functionality like `linter` and `language` packages. Would you like to join us on [AtomBuild](atombuild.github.io) to make `build-gradle` and `build` better packages.

By helping us this, you could help make all `build` providers function better due to the modular nature of `build`.

Feel free to comment on this issue or shoot me an email if you have any questions or concerns. I also frequent the atom.io Slack.

**Comment by springeye** [comment]
@kepler0 Thank you very much, I am a beginner, start to learn and use atom-build

**Comment by keplersj** [comment]
I can add you as a member of the @AtomBuild organization if you would like.

**Comment by benjaminRomano** [comment]
Nice package. Good use of bottom-dock :smile:

**Comment by springeye** [comment]
@benjaminRomano hahaha

It is true that you can't use the new version, you can pull the v0.0.2 tag code for this project. Then just modify the package.json

``` json
"atom-bottom-dock": "^0.5.2",
.....
"bottom-dock": "0.3.5"
```

then atom error will appear reload.
Because I was a beginner, I also specifically looked at [behind-atom-interacting-with-packages-via-services](https://atom.io/docs/v1.0.4/behind-atom-interacting-with-packages-via-services)

**Comment by benjaminRomano** [comment]
I fixed the bug. See https://github.com/benjaminRomano/atom-bottom-dock/issues/1
